# Generated by Django 4.0.6 on 2022-11-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_alter_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probationer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='User name')),
                ('user_id', models.IntegerField(verbose_name='Telegram id')),
                ('end_time', models.IntegerField(verbose_name='Time to goodbye')),
                ('answers', models.TextField(verbose_name='True variants')),
                ('success', models.BooleanField(null=True, verbose_name='Success guess?')),
                ('actual', models.BooleanField(default=True, verbose_name='Actual event?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of event')),
            ],
        ),
    ]
