# Generated by Django 4.0.6 on 2022-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0003_probationer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probationer',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Telegram id'),
        ),
    ]
