# Generated by Django 4.0.6 on 2022-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0004_alter_probationer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probationer',
            name='success',
            field=models.BooleanField(default=None, null=True, verbose_name='Success guess?'),
        ),
    ]
