# Generated by Django 4.0.5 on 2022-06-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('salary_from', models.PositiveIntegerField(null=True)),
                ('salary_to', models.PositiveIntegerField(null=True)),
                ('schedule', models.CharField(max_length=50)),
                ('employer_name', models.CharField(max_length=150)),
                ('published_at', models.DateTimeField()),
                ('url', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='JobsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.SlugField()),
            ],
        ),
    ]
