# Generated by Django 4.0.5 on 2022-06-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobssource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobssource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobssource',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
