# Generated by Django 4.0.5 on 2022-06-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_source_jobssource_is_active_alter_jobs_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
