# Generated by Django 4.0.5 on 2022-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
