# Generated by Django 4.0.5 on 2022-06-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechWorkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TechWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techworks.techworksource')),
            ],
        ),
    ]
