# Generated by Django 4.0.5 on 2022-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techworks', '0003_techwork_time_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techwork',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='techwork',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
    ]
