# Generated by Django 4.0.5 on 2022-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techworks', '0004_alter_techwork_end_time_alter_techwork_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='techwork',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новое'),
        ),
    ]
